version: '3.4'

services:
  dev:
    build: .
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - "8080:8080"

  test:
    build: .
    volumes:
      - .:/app
    command: yarn unit --maxWorkers=4

  test-circle:
    build: .
    environment:
      - CI=true
    volumes:
      - ./test/unit/specs/__image_snapshots__/__diff_output__:/app/test/unit/specs/__image_snapshots__/__diff_output__
    command: yarn unit --maxWorkers=8
