version: '3.4'

services:
  test:
    build: .
    volumes:
      - .:/app
    entrypoint: [sh, /app/test-entrypoint.sh, --maxWorkers=4]

  test-update:
    build: .
    volumes:
      - .:/app
    entrypoint: [sh, /app/test-entrypoint.sh, --maxWorkers=4, -u]

  test-ci:
    build: .
    environment:
      - CI=true
    entrypoint: [sh, /app/test-entrypoint.sh, --maxWorkers=4, -u, --reporters=default, --reporters=jest-junit]
