version: '3.4'

services:
  test:
    build: .
    volumes:
      - .:/app
    command: [sh, -c, "yarn build-view && yarn unit --maxWorkers=4"]

  test-update:
    build: .
    volumes:
      - .:/app
    command: [sh, -c, "yarn build-view && yarn unit --maxWorkers=4 -u"]

  test-ci:
    build: .
    environment:
      - CI=true
    command: [sh, -c, "yarn build-view && yarn unit --maxWorkers=4 --reporters=default --reporters=jest-junit"]
