version: '3.4'

services:
  test:
    build: .
    volumes:
      - .:/app
    command: [sh, -c, "yarn build-view && yarn unit --maxWorkers=4"]

  test-update:
    build: .
    volumes:
      - .:/app
    command: [sh, -c, "yarn build-view && yarn unit --maxWorkers=4 -u"]

  test-ci:
    build: .
    environment:
      - CI=true
      - JEST_JUNIT_OUTPUT=/tmp/test-results
    command: [sh, -c, "yarn build-view && yarn unit --maxWorkers=4"]
