jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout

      - run: docker-compose up test

      - store_artifacts:
          path: /home/circleci/project/test/unit/specs/__image_snapshots__/__diff_output__
          destination: image-diff

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
