version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Run tests
          command: docker-compose run circle

      - run:
          name: Docker ps
          when: on_fail
          command: docker ps -a


      - run:
          name: Copy image diffs
          when: on_fail
          command: docker cp project_circle_run_1:test/unit/specs/__image_snapshots__ /image-diff 

      - store_artifacts:
          path: /image-diff
          destination: image-diff

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
