jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout

      - run: npm install
      - run: npm run unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
