version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    # parallelism: 1

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Run tests
          command: docker-compose run --name circle test-ci

      - run:
          name: Copy test results
          when: always
          command: |
            mkdir -p /tmp/test-results/jest
            docker cp circle:/app/junit.xml /tmp/test-results/jest/results.xml

      - run:
          name: Copy artifacts
          when: on_fail
          command: |
            docker cp circle:/app/test/unit/specs/__image_snapshots__/__diff_output__ /tmp/image-diff

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/image-diff
          destination: image-diff

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
