version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    # parallelism: 1

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Run tests
          command: docker-compose run --name circle test-ci

      - run:
          name: Copy artifacts
          when: on_fail
          command: docker cp circle:/app/test/unit/specs/__image_snapshots__/__diff_output__ /tmp/image_diffs

      - store_artifacts:
          path: /tmp/image_diffs
          destination: image-diff

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
