version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout

      - setup_remote_docker

      - run: docker-compose run test-circle

      - run:
         name: Code Has Arrived
         command: |
           ls -al
           echo '^^^That should look familiar^^^'

      - store_artifacts:
          path: app/test/unit/specs/__image_snapshots__/__diff_output__
          destination: image-diff

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
