version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout

      - setup_remote_docker

      - run:
         name: Code Has Arrived
         command: |
           ls -al test/unit/specs/__image_snapshots__
           echo '^^^That should look familiar^^^'

      - run:
          name: Run tests
          command: docker-compose run test-circle

      - run:
          name: Copy image diffs
          when: on_fail
          command: docker cp app:/output /app/test/unit/specs/__image_snapshots__/__diff_output__

      - store_artifacts:
          path: /output
          destination: image-diff

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
